Repository martin226/uptone, pull requests merged in 2022-05, with the labels that each got.

#2 feat: website project setup
  .github/semantic.yml
  .github/workflows/website.yml
  vetur.config.js
  website/.eslintrc.js
  website/.husky/commit-msg
  website/.husky/common.sh
  website/.husky/pre-commit
  website/.prettierignore
  website/.prettierrc
  website/README.md
  website/commitlint.config.js
  website/nuxt.config.js
  website/package.json
  website/pages/index.vue
  website/static/favicon.ico
  website/store/README.md
  website/stylelint.config.js
  website/tsconfig.json
  website/windi.config.ts
  website/yarn.lock
Labels: enhancement

#6 feat: backend api
  .github/workflows/api.yml
  .gitignore
  api/api/__init__.py
  api/api/consts.py
  api/api/predict.py
  api/api/preprocess.py
  api/api/sentiment.py
  api/poetry.lock
  api/pyproject.toml
  api/tests/__init__.py
  api/tests/test_api.py
Labels: enhancement

#11 fix: backend api bugs
  api/api/__init__.py
  api/api/predict.py
  api/poetry.lock
  api/pyproject.toml
Labels: bug

#4 feat: hate speech model
  notebooks/hatespeech.ipynb
Labels: enhancement

#13 feat: website
  .github/workflows/deploy.yml
  website/assets/img/ahtesham.png
  website/assets/img/emily.png
  website/assets/img/logo.svg
  website/assets/img/martin.png
  website/assets/img/nicholas.png
  website/assets/img/step_1.png
  website/assets/img/step_2.png
  website/assets/img/step_3.png
  website/assets/img/undraw_love_re_mwbq.svg
  website/components/About.vue
  website/components/Footer.vue
  website/components/Hero.vue
  website/components/How.vue
  website/components/Mission.vue
  website/nuxt.config.js
  website/package-lock.json
  website/package.json
  website/pages/index.vue
  website/static/favicon.ico
  website/windi.config.ts
Labels: enhancement

#8 feat: extension
  .github/workflows/extension.yml
  extension/.eslintrc.json
  extension/.parcelrc
  extension/.prettierignore
  extension/.prettierrc
  extension/.terserrc
  extension/package.json
  extension/src/background.js
  extension/src/content.js
  extension/src/icon.png
  extension/src/manifest.json
  extension/src/options-storage.js
  extension/src/options.css
  extension/src/options.html
  extension/src/options.js
  extension/yarn.lock
Labels: enhancement

#15 docs: update README.md
  README.md
  docs/logo.png
Labels: documentation
